language: php

php:
  - 5.6
  - 7.1

matrix:
  allow_failures:
    - php: 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer global require "fxp/composer-asset-plugin:^1.1.1"
  - composer self-update
  - composer install --prefer-dist
  - ulimit -c unlimited || true

before_script:
  # Start up a web server.
  #- php -S 127.0.0.1:8888 -t public router.php >/dev/null 2>&1 &
  # Start up the webdriver.
  #- phantomjs --webdriver=4444 >/dev/null 2>&1 &
  # Install Codeception.
  # Doing this last gives the webdriver and server time to start up.
  #- composer install --prefer-source
  - sleep 10

script:
  - php vendor/bin/codecept run  --coverage --coverage-xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
